package br.com.cidandrade.aulas.gui;

import br.com.cidandrade.aulas.classes.CjtoDados;
import br.com.cidandrade.aulas.classes.Estacao;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author cidandrade
 */
public class MetereologiaGUI extends javax.swing.JFrame
        implements PropertyChangeListener {

    Estacao estacao;

    /**
     * Creates new form MetereologiaGUI
     */
    public MetereologiaGUI() {
        initComponents();
        estacao = new Estacao();
        estacao.registrarObservador(this);
        jifDisplay.setVisible(false);
        jifEstacao.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpDesktop = new javax.swing.JDesktopPane();
        jifDisplay = new javax.swing.JInternalFrame();
        jlTemperatura = new javax.swing.JLabel();
        jtTemperatura = new javax.swing.JTextField();
        jlUmidade = new javax.swing.JLabel();
        jtUmidade = new javax.swing.JTextField();
        jifEstacao = new javax.swing.JInternalFrame();
        jbTempUp = new javax.swing.JButton();
        jbTempDown = new javax.swing.JButton();
        jbUmidDown = new javax.swing.JButton();
        jbUmidUp = new javax.swing.JButton();
        jmbMenu = new javax.swing.JMenuBar();
        jmAplicacao = new javax.swing.JMenu();
        jmApFechar = new javax.swing.JMenuItem();
        jmJanelas = new javax.swing.JMenu();
        jmJnDisplay = new javax.swing.JMenuItem();
        jmJnEstacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifDisplay.setIconifiable(true);
        jifDisplay.setResizable(true);
        jifDisplay.setTitle("Display");
        jifDisplay.setVisible(true);

        jlTemperatura.setText("Temperatura");

        jtTemperatura.setEditable(false);
        jtTemperatura.setText("25.0ºC");

        jlUmidade.setText("Umidade");

        jtUmidade.setEditable(false);
        jtUmidade.setText("60.0%");

        javax.swing.GroupLayout jifDisplayLayout = new javax.swing.GroupLayout(jifDisplay.getContentPane());
        jifDisplay.getContentPane().setLayout(jifDisplayLayout);
        jifDisplayLayout.setHorizontalGroup(
            jifDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTemperatura)
                    .addComponent(jtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUmidade)
                    .addComponent(jtUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jifDisplayLayout.setVerticalGroup(
            jifDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTemperatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlUmidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jifEstacao.setIconifiable(true);
        jifEstacao.setResizable(true);
        jifEstacao.setTitle("Estação");
        jifEstacao.setVisible(true);

        jbTempUp.setText("Temp +");
        jbTempUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTempUpActionPerformed(evt);
            }
        });

        jbTempDown.setText("Temp -");
        jbTempDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTempDownActionPerformed(evt);
            }
        });

        jbUmidDown.setText("Umid -");
        jbUmidDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUmidDownActionPerformed(evt);
            }
        });

        jbUmidUp.setText("Umid +");
        jbUmidUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUmidUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifEstacaoLayout = new javax.swing.GroupLayout(jifEstacao.getContentPane());
        jifEstacao.getContentPane().setLayout(jifEstacaoLayout);
        jifEstacaoLayout.setHorizontalGroup(
            jifEstacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifEstacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifEstacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbTempUp)
                    .addComponent(jbTempDown)
                    .addComponent(jbUmidUp)
                    .addComponent(jbUmidDown))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jifEstacaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbTempDown, jbTempUp, jbUmidDown, jbUmidUp});

        jifEstacaoLayout.setVerticalGroup(
            jifEstacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifEstacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbTempUp)
                .addGap(18, 18, 18)
                .addComponent(jbTempDown)
                .addGap(18, 18, 18)
                .addComponent(jbUmidUp)
                .addGap(18, 18, 18)
                .addComponent(jbUmidDown)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jdpDesktop.setLayer(jifDisplay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpDesktop.setLayer(jifEstacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpDesktopLayout = new javax.swing.GroupLayout(jdpDesktop);
        jdpDesktop.setLayout(jdpDesktopLayout);
        jdpDesktopLayout.setHorizontalGroup(
            jdpDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpDesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jifDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jifEstacao)
                .addContainerGap())
        );
        jdpDesktopLayout.setVerticalGroup(
            jdpDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpDesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdpDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jifDisplay)
                    .addComponent(jifEstacao))
                .addContainerGap())
        );

        jmAplicacao.setText("Aplicação");

        jmApFechar.setText("Fechar");
        jmApFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmApFecharActionPerformed(evt);
            }
        });
        jmAplicacao.add(jmApFechar);

        jmbMenu.add(jmAplicacao);

        jmJanelas.setText("Janelas");

        jmJnDisplay.setText("Display");
        jmJnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJnDisplayActionPerformed(evt);
            }
        });
        jmJanelas.add(jmJnDisplay);

        jmJnEstacao.setText("Estação");
        jmJnEstacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJnEstacaoActionPerformed(evt);
            }
        });
        jmJanelas.add(jmJnEstacao);

        jmbMenu.add(jmJanelas);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmJnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJnDisplayActionPerformed
        jifDisplay.setVisible(true);
    }//GEN-LAST:event_jmJnDisplayActionPerformed

    private void jmJnEstacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJnEstacaoActionPerformed
        jifEstacao.setVisible(true);
    }//GEN-LAST:event_jmJnEstacaoActionPerformed

    private void jmApFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmApFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmApFecharActionPerformed

    private void jbTempUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTempUpActionPerformed
        estacao.aumentarTemperatura();
    }//GEN-LAST:event_jbTempUpActionPerformed

    private void jbTempDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTempDownActionPerformed
        estacao.diminuirTemperatura();
    }//GEN-LAST:event_jbTempDownActionPerformed

    private void jbUmidUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUmidUpActionPerformed
        estacao.aumentarUmidade();
    }//GEN-LAST:event_jbUmidUpActionPerformed

    private void jbUmidDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUmidDownActionPerformed
        estacao.diminuirUmidade();
    }//GEN-LAST:event_jbUmidDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetereologiaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetereologiaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetereologiaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetereologiaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetereologiaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbTempDown;
    private javax.swing.JButton jbTempUp;
    private javax.swing.JButton jbUmidDown;
    private javax.swing.JButton jbUmidUp;
    private javax.swing.JDesktopPane jdpDesktop;
    private javax.swing.JInternalFrame jifDisplay;
    private javax.swing.JInternalFrame jifEstacao;
    private javax.swing.JLabel jlTemperatura;
    private javax.swing.JLabel jlUmidade;
    private javax.swing.JMenuItem jmApFechar;
    private javax.swing.JMenu jmAplicacao;
    private javax.swing.JMenu jmJanelas;
    private javax.swing.JMenuItem jmJnDisplay;
    private javax.swing.JMenuItem jmJnEstacao;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JTextField jtTemperatura;
    private javax.swing.JTextField jtUmidade;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evento) {
        CjtoDados dados = (CjtoDados) evento.getNewValue();
        jtTemperatura.setText(String.valueOf(dados.getTemperatura())
                + "ºC");
        jtUmidade.setText(String.valueOf(dados.getUmidade() + "%"));
    }
}
